### ISSUE TITLE
Graph evaluation mode 'multiprocessing' with graph inside node causes PicklingError

### ISSUE THREAD

**Issue by theFlyingCat04** [PaulSchweizer/flowpipe#168]
**Describe the bug**
We are wrapping graphs into nodes. This way we can time the execution of parts of the program better since we create the graphs dynamically according to yaml configuration files. If the outermost graph is evaluated in "linear" or "threading" mode everything works fine. But using "multiprocessing" mode throws an Exception, a PicklingError to be more certain.

**To Reproduce**
Minimal example showing the behaviour:
```python
from flowpipe import Graph, Node

@Node(outputs=["dummy"])
def normal_node(dummy):
    print("normal_node", flush=True)
    return {"dummy": dummy}

@Node(outputs=["dummy"])
def container_node(inner_graph, dummy):
    print(f"--- {inner_graph.name} ---", flush=True)
    inner_graph.evaluate(mode="linear")
    return {"dummy": dummy}

inner_graph = Graph(name="inner graph")
normal_node(name="inner graph node", graph=inner_graph)
container_graph = Graph(name="container graph")
container_node(name="container graph node", inner_graph=inner_graph, graph=container_graph)

print("=== linear ===")
container_graph.evaluate(mode="linear") # works
print("=== threading ===")
container_graph.evaluate(mode="threading") # works
print("=== multiprocessing ===")
container_graph.evaluate(mode="multiprocessing") # raises PicklingError
```
Output:
```
=== linear ===
--- inner graph ---
normal_node
=== threading ===
--- inner graph ---
normal_node
=== multiprocessing ===
Traceback (most recent call last):
  File "/workspaces/tests etc/test/flowpipe_container_parallel_minimal.py", line 24, in <module>
    container_graph.evaluate(mode="multiprocessing") # raises PicklingError
  File "/usr/local/lib/python3.10/site-packages/flowpipe/graph.py", line 321, in evaluate
    evaluator.evaluate(graph=self, skip_clean=skip_clean)
  File "/usr/local/lib/python3.10/site-packages/flowpipe/evaluator.py", line 49, in evaluate
    self._evaluate_nodes(nodes)
  File "/usr/local/lib/python3.10/site-packages/flowpipe/evaluator.py", line 182, in _evaluate_nodes
    nodes_data[node.identifier] = node.to_json()
  File "<string>", line 2, in __setitem__
  File "/usr/local/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function normal_node at 0x7f8c7c8c7ac0>: it's not the same object as __main__.normal_node
```

**Expected behavior**
Successfull execution without Exceptions :)

**Suggestions for Solution**
No clue...

**Comment by theFlyingCat04** [comment]
Any updates available on this issue?

**Comment by ws-jbenda** [comment]
I'd also like to know if there's any advancement on this bug, since I too get the PicklingError?

**Comment by neuneck** [comment]
Can you try subclassing `INode`, rather than using the `@Node`decorator?

The pickle module does work nicely with closures or factories, since it needs to be able to import all pickled objects' types from the source code upon unpickling.

I'm not at my work laptop right now, so I can't try this for myself.

**Comment by theFlyingCat04** [comment]
In the minimal example above this wouldn't be a problem at all. Just write
```python
from flowpipe import Graph, INode, InputPlug, OutputPlug

class normal_node(INode):
    def __init__(self, **kwargs):
        super(normal_node, self).__init__(**kwargs)
        InputPlug("dummy", self)
        OutputPlug("dummy", self)

    def compute(self, dummy):
        print("normal_node", flush=True)
        return {"dummy": dummy}

class container_node(INode):
    def __init__(self, inner_graph: Graph = None, **kwargs):
        super(container_node, self).__init__(**kwargs)
        InputPlug("dummy", self)
        OutputPlug("dummy", self)
        InputPlug("inner_graph", self, inner_graph)

    def compute(self, dummy, inner_graph: Graph):
        print(f"--- {inner_graph.name} ---", flush=True)
        inner_graph.evaluate(mode="linear")
        return {"dummy": dummy}


inner_graph = Graph(name="inner graph")
normal_node(name="inner graph node", graph=inner_graph)
container_graph = Graph(name="container graph")
container_node(name="container graph node", inner_graph=inner_graph, graph=container_graph)

print("=== linear ===")
container_graph.evaluate(mode="linear") # works
print("=== threading ===")
container_graph.evaluate(mode="threading") # works
print("=== multiprocessing ===")
container_graph.evaluate(mode="multiprocessing") # works
```
and You are good to go.

The problem I have with my real code is that I have a plugin architecture where i just import a single function from a python module and wrap it in a framework inside a `FunctionNode`. This has the benefit of being able to test a single piece of code independent from other plugins or the flowpipe framework. Changing to the INode subclass idea would cause to force each Plugin to be in this INode Subclass design. On the other hand it is super handy to just write e. g. `def plugin_main(arg1, arg2, arg3)` in a Plugin and not needing to know how much arguments each function needs since FunctionNode does that work for me.

**Comment by PaulSchweizer** [comment]
Thanks for the example and sorry for the long silence, I will try to find some time this or next week to look into this.

**Comment by PaulSchweizer** [comment]
I took a look, thanks @neuneck for pointing out the core issue. Since this is a hard limitation, we can not make the @Node decorator work under the described circumstances, but here is a simple alternative that might solve your issue, although it requires a little bit of rework:

```python
from flowpipe.node import FunctionNode

def normal_node_func(dummy):
    return {"dummy": dummy}

normal_node = FunctionNode(func=normal_node_func, outputs=["dummy"])
```

That way you retain the simple functions that you are talking about and basically just use the FuntionNode directly instead of implicitely through the decorator. Let me know if this approach would solve your issue?

**Comment by PaulSchweizer** [comment]
@theFlyingCat04 thanks for the report, this was indeed not implemented correctly, please look at this PR, it should fix the issue: https://github.com/PaulSchweizer/flowpipe/pull/170

**Comment by theFlyingCat04** [comment]
Yes, that would definitely be a benefit :smile:

**Comment by PaulSchweizer** [comment]
Do we need an exception though? The outlined fix would solve the issue, or is there still something that I am missing?

**Comment by neuneck** [comment]
If I understand correctly, using the `@Node` decorator with the multiprocessing evaluator will still not work, and have the user face nondescript errors from the `pickle` library, making it hard to understand that the `@Node` decorator is the culprit.
An error message in case a FunctionNode was created using the decorator (probably by catching and re-raising the `pickle` error) will help users find the issue in their usage pattern.

**Comment by PaulSchweizer** [comment]
`@Node`s themselves can be evaluated with multiprocessing. 

The problem is the input consists of `@Node` objects. These can not be unpickled because the object was created on the fly and when unpickling in a new process, the `@Node` class is different from the originally pickled class. 

It's a pickle behaviour and pickle is used by multiprocessing itself in this case, so I don't see that we can or should do anything in flowpipe other than the bug fix in the PR. Identifying this problem would also be really difficult, we would have to check each input for unpicklability in a new process, because unpickling in the same process would work ...

**Comment by neuneck** [comment]
I was thinking of something along the lines of
```
try:
   ... #  evaluate graph in multiprocessing
except PicklingError as exc:
    raise FlowpipeMultiprocessingError("Error pickling/unpickling nodes. Locally defined functions do not work with the multiprocessing backend. This sometimes occurs when using the @Node decorator.") from exc
```
Just to prevent people from being frustrated with code behavior / exceptions they don't understand.
(Also, when you google the pickle library, you'll find a ton of warnings about it being dangerous, so users might get the wrong impression.)

**Comment by PaulSchweizer** [comment]
@theFlyingCat04 this is now released in v1.0.0, please let me know if anything is still amiss.

Thanks also to you @neuneck for contributing and reviewing!
